# Generated by Django 4.2.11 on 2026-02-15 13:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('livreur', 'Livreur'), ('commercial', 'Commercial'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MaCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_course', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lieu_depart', models.CharField(max_length=255)),
                ('lieu_arrivee', models.CharField(max_length=255)),
                ('latitude_depart', models.FloatField(blank=True, null=True)),
                ('longitude_depart', models.FloatField(blank=True, null=True)),
                ('latitude_arrivee', models.FloatField(blank=True, null=True)),
                ('longitude_arrivee', models.FloatField(blank=True, null=True)),
                ('latitude_actuelle', models.FloatField(blank=True, null=True)),
                ('longitude_actuelle', models.FloatField(blank=True, null=True)),
                ('type_livraison', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('nature_colis', models.CharField(max_length=100)),
                ('description_colis', models.TextField(blank=True)),
                ('nom_destinataire', models.CharField(max_length=150)),
                ('telephone_destinataire', models.CharField(max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('temps_estime', models.IntegerField(blank=True, help_text='Temps estimé en minutes', null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('attente', 'En attente'), ('enroute', 'En route vers client'), ('encours', 'En cours de livraison'), ('livre', 'Livré'), ('annule', 'Annulé')], default='attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_client', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_livreur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivreurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_permis', models.CharField(blank=True, max_length=50, null=True)),
                ('date_expiration_permis', models.DateField(blank=True, null=True)),
                ('type_vehicule', models.CharField(choices=[('moto', '🏍️ Moto'), ('velo', '🚲 Vélo'), ('voiture', '🚗 Voiture'), ('scooter', '🛵 Scooter')], default='moto', max_length=20)),
                ('immatriculation', models.CharField(blank=True, max_length=50, null=True)),
                ('modele_vehicule', models.CharField(blank=True, max_length=100, null=True)),
                ('marque_vehicule', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_couverture', models.CharField(blank=True, max_length=200, null=True)),
                ('disponibilite', models.BooleanField(default=True)),
                ('numero_compte_bancaire', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('active', 'Actif'), ('blocked', 'Bloqué')], default='en_attente', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse_entreprise', models.TextField(blank=True, null=True)),
                ('type_partenariat', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires_ouverture', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='commerciaux/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('active', 'Actif'), ('blocked', 'Bloqué')], default='en_attente', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
