# Generated by Django 4.2.11 on 2026-02-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macourse',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
