# Generated by Django 4.2.11 on 2026-02-24 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_macourse_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='macourse',
            name='livreurs_ayant_refuse',
            field=models.ManyToManyField(blank=True, related_name='courses_refusees', to=settings.AUTH_USER_MODEL),
        ),
    ]
