# Generated by Django 4.2.11 on 2026-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_macourse_livreurs_ayant_refuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='macourse',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
