# Generated by Django 4.2.11 on 2026-03-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_macourse_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='macourse',
            name='date_course_programmer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macourse',
            name='heure_course_programmer',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
