# Generated by Django 4.2.11 on 2026-03-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_macourse_date_course_programmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macourse',
            name='date_course_programmer',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macourse',
            name='type_livraison',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('programmer', 'Programmé')], default='standard', max_length=20),
        ),
    ]
