# Generated by Django 4.2.11 on 2026-03-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_alter_macourse_date_course_programmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='adresse_principale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
