# Generated by Django 4.2.11 on 2026-03-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_clientprofile_adresse_principale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='adresse_principale',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
