# Generated by Django 4.2.11 on 2026-04-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_alter_clientprofile_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='adresse_livraison',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='adresse_principale',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='ville',
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('rue', models.CharField(max_length=200)),
                ('quartier', models.CharField(max_length=100)),
                ('par_defaut', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_livraison', to='app_users.clientprofile')),
            ],
        ),
    ]
