# Generated by Django 4.2.11 on 2026-04-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_remove_clientprofile_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresselivraison',
            old_name='telephone',
            new_name='telephone_adresse',
        ),
    ]
